name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      DOTNET_VERSION: '6.0.x'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore SalesTax.sln

      - name: Build solution
        run: dotnet build SalesTax.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test SalesTaxTests/SalesTaxTests.csproj --no-build --verbosity normal

      - name: Publish app
        run: dotnet publish SalesTax/SalesTax.csproj --configuration Release --output ./publish
